# Generated by Django 6.0.3 on 2026-05-26 10:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('branches', '0001_initial'),
        ('subscriptions', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='subscriptionplan',
            name='name',
            field=models.CharField(db_index=True, max_length=100),
        ),
        migrations.AlterField(
            model_name='subscriptionplan',
            name='status',
            field=models.CharField(choices=[('active', 'Active'), ('archived', 'Archived')], db_index=True, default='active', max_length=20),
        ),
        migrations.AlterField(
            model_name='subscriptionplan',
            name='type',
            field=models.CharField(choices=[('individual', 'Individual'), ('group', 'Group')], db_index=True, default='individual', max_length=20),
        ),
        migrations.AddIndex(
            model_name='subscriptionplan',
            index=models.Index(fields=['branch', 'type', 'status'], name='subplan_branch_type_status_idx'),
        ),
    ]
