# Generated by Django 6.0.3 on 2026-04-07 13:56

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('students_and_groups', '0001_initial'),
    ]

    operations = [
        migrations.RemoveConstraint(
            model_name='groupmembership',
            name='unique_group_student_membership',
        ),
    ]
