# Generated by Django 6.0.3 on 2026-05-26 10:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('branches', '0001_initial'),
        ('students_and_groups', '0002_remove_groupmembership_unique_group_student_membership'),
    ]

    operations = [
        migrations.AlterField(
            model_name='group',
            name='name',
            field=models.CharField(db_index=True, max_length=100),
        ),
        migrations.AlterField(
            model_name='group',
            name='status',
            field=models.CharField(choices=[('active', 'Active'), ('archived', 'Archived')], db_index=True, default='active', max_length=20),
        ),
        migrations.AlterField(
            model_name='student',
            name='first_name',
            field=models.CharField(db_index=True, max_length=50),
        ),
        migrations.AlterField(
            model_name='student',
            name='last_name',
            field=models.CharField(db_index=True, max_length=50),
        ),
        migrations.AlterField(
            model_name='student',
            name='status',
            field=models.CharField(choices=[('active', 'Active'), ('archived', 'Archived')], db_index=True, default='active', max_length=20),
        ),
        migrations.AddIndex(
            model_name='group',
            index=models.Index(fields=['branch', 'status'], name='group_branch_status_idx'),
        ),
        migrations.AddIndex(
            model_name='student',
            index=models.Index(fields=['branch', 'status'], name='student_branch_status_idx'),
        ),
    ]
